# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui/MainWindow.ui'
#
# Created: Mon Jun  8 01:18:55 2015
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(467, 612)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButtonExit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonExit.setIconSize(QtCore.QSize(15, 15))
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.gridLayout_8.addWidget(self.pushButtonExit, 2, 0, 1, 3)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEditProjectLocation = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditProjectLocation.setReadOnly(True)
        self.lineEditProjectLocation.setPlaceholderText("")
        self.lineEditProjectLocation.setObjectName("lineEditProjectLocation")
        self.gridLayout.addWidget(self.lineEditProjectLocation, 0, 1, 1, 2)
        self.toolButtonLocation = QtWidgets.QToolButton(self.groupBox)
        self.toolButtonLocation.setObjectName("toolButtonLocation")
        self.gridLayout.addWidget(self.toolButtonLocation, 0, 3, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButtonNew = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonNew.setObjectName("pushButtonNew")
        self.gridLayout_3.addWidget(self.pushButtonNew, 0, 0, 1, 1)
        self.pushButtonLoad = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.gridLayout_3.addWidget(self.pushButtonLoad, 0, 1, 1, 1)
        self.pushButtonUpdate = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        self.gridLayout_3.addWidget(self.pushButtonUpdate, 0, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEditMemorySize = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditMemorySize.setInputMask("")
        self.lineEditMemorySize.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditMemorySize.setObjectName("lineEditMemorySize")
        self.gridLayout_5.addWidget(self.lineEditMemorySize, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 1, 0, 1, 1)
        self.lineEditDataSegSize = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEditDataSegSize.setInputMask("")
        self.lineEditDataSegSize.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditDataSegSize.setObjectName("lineEditDataSegSize")
        self.gridLayout_5.addWidget(self.lineEditDataSegSize, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 2, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_4, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.comboBoxOptimization = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxOptimization.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxOptimization.setObjectName("comboBoxOptimization")
        self.comboBoxOptimization.addItem("")
        self.comboBoxOptimization.addItem("")
        self.comboBoxOptimization.addItem("")
        self.comboBoxOptimization.addItem("")
        self.comboBoxOptimization.addItem("")
        self.gridLayout_6.addWidget(self.comboBoxOptimization, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEditCompilerPrefix = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditCompilerPrefix.setObjectName("lineEditCompilerPrefix")
        self.gridLayout_2.addWidget(self.lineEditCompilerPrefix, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEditCompilerPath = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditCompilerPath.setObjectName("lineEditCompilerPath")
        self.gridLayout_2.addWidget(self.lineEditCompilerPath, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_3, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.pushButtonOpenPort = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOpenPort.sizePolicy().hasHeightForWidth())
        self.pushButtonOpenPort.setSizePolicy(sizePolicy)
        self.pushButtonOpenPort.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButtonOpenPort.setObjectName("pushButtonOpenPort")
        self.gridLayout_12.addWidget(self.pushButtonOpenPort, 0, 2, 1, 1)
        self.comboBoxSerialPort = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBoxSerialPort.setObjectName("comboBoxSerialPort")
        self.gridLayout_12.addWidget(self.comboBoxSerialPort, 0, 0, 1, 1)
        self.pushButtonReload = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonReload.sizePolicy().hasHeightForWidth())
        self.pushButtonReload.setSizePolicy(sizePolicy)
        self.pushButtonReload.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButtonReload.setObjectName("pushButtonReload")
        self.gridLayout_12.addWidget(self.pushButtonReload, 0, 1, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.toolButtonSeletBinFile = QtWidgets.QToolButton(self.groupBox_6)
        self.toolButtonSeletBinFile.setObjectName("toolButtonSeletBinFile")
        self.gridLayout_11.addWidget(self.toolButtonSeletBinFile, 0, 1, 1, 1)
        self.lineEditBinFile = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEditBinFile.setReadOnly(True)
        self.lineEditBinFile.setObjectName("lineEditBinFile")
        self.gridLayout_11.addWidget(self.lineEditBinFile, 0, 0, 1, 1)
        self.pushButtonBoot = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButtonBoot.setEnabled(True)
        self.pushButtonBoot.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButtonBoot.setObjectName("pushButtonBoot")
        self.gridLayout_11.addWidget(self.pushButtonBoot, 0, 2, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_10.addWidget(self.textEdit, 0, 0, 1, 1)
        self.pushButtonClear = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.gridLayout_10.addWidget(self.pushButtonClear, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_8.addWidget(self.tabWidget, 1, 0, 1, 3)
        self.labelIcon = QtWidgets.QLabel(self.centralwidget)
        self.labelIcon.setMaximumSize(QtCore.QSize(220, 73))
        self.labelIcon.setScaledContents(True)
        self.labelIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.labelIcon.setObjectName("labelIcon")
        self.gridLayout_8.addWidget(self.labelIcon, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEditProjectLocation, self.pushButtonNew)
        MainWindow.setTabOrder(self.pushButtonNew, self.pushButtonLoad)
        MainWindow.setTabOrder(self.pushButtonLoad, self.pushButtonUpdate)
        MainWindow.setTabOrder(self.pushButtonUpdate, self.lineEditCompilerPrefix)
        MainWindow.setTabOrder(self.lineEditCompilerPrefix, self.lineEditCompilerPath)
        MainWindow.setTabOrder(self.lineEditCompilerPath, self.comboBoxOptimization)
        MainWindow.setTabOrder(self.comboBoxOptimization, self.lineEditMemorySize)
        MainWindow.setTabOrder(self.lineEditMemorySize, self.lineEditDataSegSize)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "C project"))
        self.pushButtonExit.setText(_translate("MainWindow", "E&xit"))
        self.groupBox.setTitle(_translate("MainWindow", "Project"))
        self.label_2.setText(_translate("MainWindow", "Location"))
        self.toolButtonLocation.setText(_translate("MainWindow", "..."))
        self.pushButtonNew.setText(_translate("MainWindow", "&New"))
        self.pushButtonLoad.setText(_translate("MainWindow", "&Load"))
        self.pushButtonUpdate.setText(_translate("MainWindow", "&Update"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Target Memory"))
        self.lineEditMemorySize.setText(_translate("MainWindow", "16384"))
        self.label_6.setText(_translate("MainWindow", "Memory Size"))
        self.lineEditDataSegSize.setText(_translate("MainWindow", "2048"))
        self.label_8.setText(_translate("MainWindow", "Data Segment Size"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Optimization Level"))
        self.comboBoxOptimization.setItemText(0, _translate("MainWindow", "Default (-O0)"))
        self.comboBoxOptimization.setItemText(1, _translate("MainWindow", "Minimal (-O1)"))
        self.comboBoxOptimization.setItemText(2, _translate("MainWindow", "More (-O2)"))
        self.comboBoxOptimization.setItemText(3, _translate("MainWindow", "Standard (-O3)"))
        self.comboBoxOptimization.setItemText(4, _translate("MainWindow", "For Size (-Os)"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Compiler"))
        self.label_3.setText(_translate("MainWindow", "Prefix"))
        self.lineEditCompilerPrefix.setText(_translate("MainWindow", "mips-sde-elf-"))
        self.label_4.setText(_translate("MainWindow", "Location"))
        self.lineEditCompilerPath.setText(_translate("MainWindow", "/opt/mgc/embedded/codebench"))
        self.lineEditCompilerPath.setPlaceholderText(_translate("MainWindow", "<if not in path>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Project"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Serial Port"))
        self.pushButtonOpenPort.setText(_translate("MainWindow", "&Open"))
        self.pushButtonReload.setText(_translate("MainWindow", "&Reload"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Bin File"))
        self.toolButtonSeletBinFile.setText(_translate("MainWindow", "..."))
        self.lineEditBinFile.setPlaceholderText(_translate("MainWindow", "Select BIN File"))
        self.pushButtonBoot.setText(_translate("MainWindow", "&Boot"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Console"))
        self.pushButtonClear.setText(_translate("MainWindow", "&Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Bootloader"))
        self.labelIcon.setText(_translate("MainWindow", "Insert Logo"))

